// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import static myfirstmodule.proxies.constants.Constants.getMyFirstConstant;

public class MyFirstJavaAction extends CustomJavaAction<java.lang.Void>
{
	public MyFirstJavaAction(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		logDemo();
        return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "MyFirstJavaAction";
	}

	// BEGIN EXTRA CODE
    private static final ILogNode LOG = Core.getLogger(getMyFirstConstant());

    public static void logDemo() {
        LOG.info("MendixUnitTestBase usage demonstration");
    }
	// END EXTRA CODE
}
